config/routes.rb
Rails.application.routes.draw do
  resources :board_messages
  resources :board_users
  devise_for :accounts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_message.rb
class BoardMessage < ApplicationRecord
  belongs_to :board_user

  validates :content,presence:{message:'は必須項目です'}
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
  belongs_to :account
  has_many :board_message

  validates :nickname,presence:{message:'は必須項目です'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/board_messages_controller.rb
class BoardMessagesController < ApplicationController
  before_action :set_board_message, only: %i[ show edit update destroy ]
  before_action :authenticate_account!

  # GET /board_messages or /board_messages.json
  def index
    #@board_messages = BoardMessage.all
    @board_messages = BoardMessage.page(params[:page]).order('created_at desc')
    users = BoardUser.where('account_id==?',current_account.id)[0]
    if users ==nil then
      user = BoardUser.new
      user.account_id=current_account.id
      user.nickname='<<no name>>'
      user.save
      users = BoardUser.where('account_id==?',current_account.id)
    end
    @board_user=users
    @board_message=BoardMessage.new
    @board_message.board_user_id=@board_user.id
  end

  # GET /board_messages/1 or /board_messages/1.json
  def show
    redirect_to '/board_messages'
  end

  # GET /board_messages/new
  def new
    #@board_message = BoardMessage.new
    redirect_to '/board_messages'
  end

  # GET /board_messages/1/edit
  def edit
    redirect_to '/board_messages'
  end

  # POST /board_messages or /board_messages.json
  def create

    @board_messages = BoardMessage.page(params[:page]).order('created_at desc')
    @board_message = BoardMessage.new(board_message_params)
    @board_user = BoardUser.where('account_id==?',current_account.id)

    respond_to do |format|
      if @board_message.save
        #format.html { redirect_to board_message_url(@board_message), notice: "Board message was successfully created." }
        format.html { redirect_to '/board_messages'}
        format.json { render :show, status: :created, location: @board_message }
      else
        #format.html { render :new, status: :unprocessable_entity }
        format.html { render :index }
        format.json { render json: @board_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /board_messages/1 or /board_messages/1.json
  def update
    redirect_to '/board_messages'
=begin
    respond_to do |format|
      if @board_message.update(board_message_params)
        format.html { redirect_to board_message_url(@board_message), notice: "Board message was successfully updated." }
        format.json { render :show, status: :ok, location: @board_message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board_message.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # DELETE /board_messages/1 or /board_messages/1.json
  def destroy
  redirect_to '/board_messages'
=begin
    @board_message.destroy

    respond_to do |format|
      format.html { redirect_to board_messages_url, notice: "Board message was successfully destroyed." }
      format.json { head :no_content }
    end
=end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_message
      @board_message = BoardMessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_message_params
      params.require(:board_message).permit(:content, :board_user_id)
    end
end

app/controllers/board_users_controller.rb
class BoardUsersController < ApplicationController
  before_action :set_board_user, only: %i[ show edit update destroy ]
  before_action :authenticate_account!
  # GET /board_users or /board_users.json
  def index
    #@board_users = BoardUser.all
    users =  BoardUser.where 'account_id == ?',current_account.id
    if users[0] ==nil then
      user = BoardUser.new
      user.account_id = current_account.id
      user.nickname = '<<no name>>'
      user.save
      users =  BoardUser.where 'account_id == ?',current_account.id
    end
    @board_users = users[0]
  end

  # GET /board_users/1 or /board_users/1.json
  def show
    @board_user = BoardUser.find(params[:id])
  end

  # GET /board_users/new
  def new
    #@board_user = BoardUser.new
    redirect_to '/board_message'
  end

  # GET /board_users/1/edit
  def edit
    redirect_to '/board_message'
  end

  # POST /board_users or /board_users.json
  def create
    redirect_to '/board_message'
=begin
    @board_user = BoardUser.new(board_user_params)

    respond_to do |format|
      if @board_user.save
        format.html { redirect_to board_user_url(@board_user), notice: "Board user was successfully created." }
        format.json { render :show, status: :created, location: @board_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board_user.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # PATCH/PUT /board_users/1 or /board_users/1.json
  def update
    respond_to do |format|
      if @board_user.update(board_user_params)
        #format.html { redirect_to board_user_url(@board_user), notice: "Board user was successfully updated." }
        format.html { redirect_to '/board_message'}
        format.json { render :show, status: :ok, location: @board_user }
      else
        #format.html { render :edit, status: :unprocessable_entity }
        format.html { render :index}
        format.json { render json: @board_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /board_users/1 or /board_users/1.json
  def destroy
    redirect_to '/board_message'
=begin
    @board_user.destroy

    respond_to do |format|
      format.html { redirect_to board_users_url, notice: "Board user was successfully destroyed." }
      format.json { head :no_content }
    end
=end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_user
      @board_user = BoardUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_user_params
      params.require(:board_user).permit(:nickname, :account_id, :memo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_messages_helper.rb
module BoardMessagesHelper
end

app/helpers/board_users_helper.rb
module BoardUsersHelper
end

app/views/board_messages/_form.html.erb
<%= form_with(model: board_message) do |form| %>
  <% if board_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_message.errors.count, "error") %> prohibited this board_message from being saved:</h2>

      <ul>
        <% board_message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :board_user_id %>
    <%= form.number_field :board_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/board_messages/edit.html.erb
<h1>Editing Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Show', @board_message %> |
<%= link_to 'Back', board_messages_path %>

app/views/board_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Board Messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Board user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @board_messages.each do |board_message| %>
      <tr>
        <td><%= board_message.content %></td>
        <td><%= board_message.board_user_id %></td>
        <td><%= link_to 'Show', board_message %></td>
        <td><%= link_to 'Edit', edit_board_message_path(board_message) %></td>
        <td><%= link_to 'Destroy', board_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board Message', new_board_message_path %>

app/views/board_messages/new.html.erb
<h1>New Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Back', board_messages_path %>

app/views/board_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @board_message.content %>
</p>

<p>
  <strong>Board user:</strong>
  <%= @board_message.board_user_id %>
</p>

<%= link_to 'Edit', edit_board_message_path(@board_message) %> |
<%= link_to 'Back', board_messages_path %>

app/views/board_users/_form.html.erb
<%= form_with(model: board_user,local:true) do |form| %>
  <% if board_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_user.errors.count, "error") %> prohibited this board_user from being saved:</h2>

      <ul>
        <% board_user.errors.full_message.each do |error| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :account_id %>

  <div class="form-group">
    <%= form.label :nickname %>
    <%= form.text_field :nickname,class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :account_id %>
    <div class="border p-1">
      <%= @board_user.account_id %>
    </div>
    <%= form.hidden_field :account_id %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/board_users/edit.html.erb
<h1>Editing Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Show', @board_user %> |
<%= link_to 'Back', board_users_path %>

app/views/board_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">User Home</h1>
<h2 class="h4"><%=@board_user.account.email %>さんの設定</h2>
<%= render 'form',board_user: @board_user %>
<hr>

<p><%=link_to '<<go back',controller:board_message%></p>

<hr>
<div>copyright SYODA-Tuyano 2022.</div>

app/views/board_users/new.html.erb
<h1>New Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Back', board_users_path %>

app/views/board_users/show.html.erb
<h1 class="display-4 text-primary">"<%=@board_user.nickname %>"</h1>
<table class="table">
  <tr>
    <th>Nickname</th>
    <td><%= @board_user.nickname %></td>
  </tr>
  <tr>
    <th>ID</th>
    <td><%= @board_user.id %></td>
  </tr>
  <tr>
    <th>Created at</th>
    <td><%= @board_user.created_at %></td>
  </tr>
  <tr>
    <th>Memo</th>
    <td><%= @board_user.memo %></td>
  </tr>
</table>
<hr>
<%= link_to '<< Back', controller: :board_message %> |
<hr>
<div>copyright SYODA-Tuyano 2022.</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewMsgboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container"> 
    <%= yield %>
  </body>
</html>